import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:myapp/services/auth_service.dart';
import 'package:myapp/services/notification_service.dart';
import 'package:provider/provider.dart';
import 'package:myapp/screens/auth/auth_wrapper.dart';
import 'package:myapp/theme.dart';

// Import the Firebase options file generated by `flutterfire configure`
import 'firebase_options.dart';

/// # Application Entry Point: main()
void main() async {
  // Ensure Flutter bindings are initialized before calling native code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the default platform options.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize locale data for date formatting.
  await initializeDateFormatting('id_ID', null);

  // Initialize the notification service and request permissions.
  final notificationService = NotificationService();
  await notificationService.initialize();
  await notificationService.requestPermissions();

  // Run the app, wrapped in providers for state management.
  runApp(const MyApp());
}

/// # Root Widget: MyApp
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Using MultiProvider to provide multiple services at the top level.
    return MultiProvider(
      providers: [
        // Provider for the authentication service.
        Provider<AuthService>(
          create: (_) => AuthService(),
        ),
        // Provider for the theme management.
        ChangeNotifierProvider<ThemeProvider>(
          create: (context) => ThemeProvider(),
        ),
        // StreamProvider to listen to authentication state changes.
        StreamProvider<User?>(
          create: (context) => context.read<AuthService>().authStateChanges,
          initialData: null,
        ),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, child) {
          return MaterialApp(
            title: 'Murojaah App',
            debugShowCheckedModeBanner: false,

            // --- Theme Configuration ---
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeProvider.themeMode,

            // --- Initial Route ---
            // The AuthWrapper will decide which screen to show first.
            home: const AuthWrapper(),
          );
        },
      ),
    );
  }
}
